cargo-features = ["named-profiles"]

[package]
name = "neutron_kernel"
version = "0.1.1"
edition = "2021"
description = "A rust-based kernel for riscv and arm"
license = "BSD-3-Clause"

[lib]
crate-type = ["staticlib"]
bench = false

[dependencies]
volatile = "0.4.4"
spin = "0.9.2"
linked_list_allocator = "0.9.0"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

# [profile.dev_riscv]
# inherits = "dev"
# panic = "abort"

# [profile.release_riscv]
# inherits = "release"
# lto = true
# panic = "abort"

# Dont place panic unwind cause it screws it up or something
[profile.test]

[dev.dependencies]
# install it instead
# arcboot = {version = "0.1.0", git = "https://github.com/SpectralProject/Arcboot.git"}
