[package]
name = "neutron_kernel"
version = "0.1.1"
edition = "2021"
description = "A full minimal kernel for risc systems"
license = "GPL-3.0-only"

# FOR INTEGRATION TESTS
# [[test]]
# name = "main"
# harness = false

[dependencies]
volatile = "0.4.4"
spin = "0.9.2"
linked_list_allocator = "0.9.0"
tock-registers = "0.7.0"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = "7.2.0"

# arcboot should already have those libraries in its runtime
# but keep for now in case of testing with qemu
[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14.9"
bootloader = "0.10.12"
uart_16550 = "0.2.0"

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv-rt = "0.8.1"

# Used by arcutils `arcutils test --neutron` for higher level testing
[features]
arctest = []
graphics = []
arcwm = []
driver_ext = []
wasm_support = []
