[package]
name = "neutron_kernel"
version = "0.1.1"
edition = "2021"
description = "A rust-based kernel for riscv and arm"
license = "GPL-3.0-only"

[lib]
crate-type = ["staticlib"]
bench = false

[dependencies]
volatile = "0.2.6"
spin = "0.9.2"
linked_list_allocator = "0.9.0"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[target.'cfg(target_arch = "riscv64")'.dependencies]
rustsbi = "0.2.2"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

# Dont place panic unwind cause it screws it up or something
[profile.test]
panic = "abort"

# Shouldnt need many dev deps. Install arcboot via cargo install arcboot
[dev.dependencies]

[features]
arctest = []
