[package]
name = "neutronkern"
version = "0.1.0"
edition = "2021"
# crate_type = "staticlib"

[dependencies]
volatile = "0.2.6"
spin = "0.5.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[build-dependencies]
cc = { version = "1.0.72", features = ["parallel"] }
