[package]
name = "neutron_main"
version = "0.1.1"
edition = "2021"
description = "A full minimal kernel for risc systems"
license = "GPL-3.0-only"

[dependencies]
neutron_kernel = { path = "neutron_kernel" }
