[toolchain]
channel = "nightly"
components = [ "rust-src", "rust-std", "llvm-tools-preview", "rustfmt", "rustc-dev" ]
targets = [ "riscv64gc-unknown-none-elf", "x86_64-unknown-none" ]
profile = "default"
