# This project should have minimal config here. Rely on Arcboot
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true

[alias]
# BUILD
# pass --release or --debug. Default is --debug
barm = "build --target aarch64-unknown-none"
brv = "build --target riscv64gc-unknown-none-elf"
bx86 = "build --target x86_64-unknown-none"
# TESTS
trv = "test --target riscv64gc-unknown-none-elf -- --nocapture --no-run"
arctestb = "rustc --target=riscv64gc-unknown-none-elf --features arctest"

[build]
out-dir = "build"

# STUFF FOR EACH ARCH
# [target.riscv64]
