# This project should have minimal config here. Rely on Arcboot
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true

[alias]
# BUILD
# pass --release or --debug. Default is --debug with multiboot
barm = "build --target aarch64-unknown-none --features multiboot"
brv = "build --target riscv64gc-unknown-none-elf"
bx86 = "build --target x86_64-unknown-none"
# RUN
rarm = "run --target aarch64-unknown-none --features multiboot"
# TESTS
trv = "test --target riscv64gc-unknown-none-elf --no-run"
# TODO: make a profile to run the tests in runner. Also account for integration tests
tarm = "test --target aarch64-unknown-none --no-run"
tx86 = "test --target x86_64-unknown-none --no-run"
# Run with arcutils test build/neutron_kernel
arctestb = "rustc --target=riscv64gc-unknown-none-elf --features arctest"

[build]
out-dir = "build"

[target.aarch64-unknown-none]
# default is multiboot
rustflags = ["-C", "link-arg=-Tbuild/multiboot_entry.ld"]
runner = "qemu-system-aarch64 -M virt -cpu cortex-a57 -nographic -kernel build/neutron_kernel -serial mon:stdio"

# STUFF FOR EACH ARCH

# [target.riscv64gc-unknown-none-elf]

# [target.x86_64-unknown-none]
