# This project should have minimal config here. Rely on Arcboot and Arcutils
[unstable]
unstable-options = true

[alias]
# BUILD. Uses -Zstd for core/alloc/builtins & mem. Pass --release or --debug. Default is --debug with limine

# Defaults
barm = "build --bin arm --target .neutron/aarch64/arm.json -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"
brv = "build --bin riscv --target .neutron/riscv/xv6.json -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"
bx86 = "build --bin x86 --target .neutron/x86/x86_64.json -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"
rx86 = "run --bin x86 --target .neutron/x86/x86_64.json -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"

# Arcboot
barmarc = "build --target .neutron/aarch64/armv8.json --features arcboot,ll_alloc -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"
brvarc = "build --target riscv64gc-unknown-none-elf --features arcboot"

# Limine
barml = "build --target aarch64-unknown-none --features limine"
bx86l = "build --target .neutron/x86/stivale.json --features limine,ll_alloc -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"

# ARCTEST. Run with arc test --neutron after cargo arctestb
arctestb = "rustc --target=riscv64gc-unknown-none-elf --features arctest"

[build]
out-dir = "build"

[target.'cfg(target_os = "neutronx86")']
runner = "bootimage runner"
