# This project should have minimal config here. Rely on Arcboot
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true

[alias]
# BUILD
# pass --release or --debug. Default is --debug
barm = "build --target aarch64-unknown-none"
brv = "build --target riscv64gc-unknown-none-elf"
bx86 = "build --target x86_64-unknown-none"
# TESTS
trv = "test --target riscv64gc-unknown-none-elf --no-run"
tarm = "test --target aarch64-unknown-none --no-run"
tx86 = "test --target x86_64-unknown-none --no-run"
# ! for now, use arctest from arcutils
arctestb = "rustc --target=riscv64gc-unknown-none-elf --features arctest"

[build]
out-dir = "build"

[target.aarch64-unknown-none]
# rustflags = ["-C", "link-arg=-Tsrc/aarch64.x"]

# STUFF FOR EACH ARCH
# [target.riscv64]
