# This project should have minimal config here. Rely on Arcboot
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true

[alias]
# BUILD
# pass --release or --debug. Default is --debug with multiboot
barm = "build --target aarch64-unknown-none --features multiboot"
brv = "build --target riscv64gc-unknown-none-elf"
bx86 = "build --target x86_64-unknown-none"
# BUILD TESTS (NO RUN)
trv = "test --target riscv64gc-unknown-none-elf --no-run"
tarm = "test --target aarch64-unknown-none --no-run"
tx86 = "test --target x86_64-unknown-none --no-run"
# BUILD ARCTEST (NO RUN)
# Run with arc test --neutron after cargo arctestb
arctestb = "rustc --target=riscv64gc-unknown-none-elf --features arctest"

[build]
out-dir = "build"

[target.aarch64-unknown-none]
runner = "arc run --neutron"

[target.features.limine]
# The basic cargo build links with stivale2
rustflags = ["-C", "link-arg=-T.neutron/aarch64/stivale2.ld"]

[target.features.arcboot]

[target.features.multiboot]

# STUFF FOR EACH ARCH

# [target.riscv64gc-unknown-none-elf]

# [target.x86_64-unknown-none]
